[app]
title = Compresseur-Auto
package.name = compresseurauto
package.domain = com.secguardian
source.dir = .
source.include_exts = py,png,jpg,jpeg
version = 1.0
requirements = python3,kivy,pil
orientation = portrait
fullscreen = 0
android.api = 34
android.minapi = 26
android.ndk = 28c
android.permissions = READ_MEDIA_IMAGES, READ_EXTERNAL_STORAGE
android.allow_backup = false
android.icon = bulkresizer.png
android.icon_bg = #0D111B
android.manifest_intent_filters =
android.wakelock = false
android.enable_androidx = true
android.use_sdl2 = true
android.enable_custom_linking = false
android.use_set_trace = true
android.copy_libs = true
android.archs = arm64-v8a
android.avoid_java_reflection = true
android.strings =
android.app_lib =
android.enable_import_scanner = true
android.presep_lib =
android.add_color =
android.add_drawable =
android.add_styles =
#android.extra_manifest_application_arguments =
android.blacklist =
android.whitelist =
android.presplash =
android.presplash_color =
android.store_username =
android.store_password =
android.key_alias =
android.key_password =
android.copyright = Copyright 2024 Espace Informatique de Vincennes
android.ndk_api = 26
android.playstore =
android.extra_java_args =
android.google_apikey =
android.google_safetynet_key =
android.google_play_services_key =
android.google_licenses_key =
android.adb_args =
android.console = false
android.log_handler = adb
android.log_level = 2

[buildozer]
log_level = 2
warn_on_root = 1
